### ISSUE TITLE
`profile_name` as Argument

### ISSUE THREAD

**Issue by clifflu** [kislyuk/watchtower#10]
*Profile* is a method to manage multiple AWS credentials for the same user, and it is extremely useful for projects in develop. I've created a feature branch at https://github.com/clifflu/watchtower/tree/feature/boto3-arguments , adding two arguments to `CloudWatchLogHandler::__init__()` as arguments to create boto3 sessions. Developers can then pass profile_name or region_name to create a customised session.

I'd like to know whether you'd prefer the current approach, or have `profile_name` and `region_name` arguments to `CloudWatchLogHandler::__init__()` so it's neater.

I'll submit a PR once it's decided. Thanks in advance.

**Comment by kislyuk** [comment]
It seems your branch is even with master. If you want me to look at a diff, please push it.

In general (given what I've learned about boto3 in the past few months) I would rather go this route:
```
class Foo:
    def __init__(self, boto3_logs_resource=None):
        if boto3_logs_resource is None:
            boto3_logs_resource = boto3.resource("logs")
        self.cwl_client = boto3_logs_resource.meta.client
        ...
```

**Comment by clifflu** [comment]
Thanks for your suggestion. I've created a pull request in that pattern.

The PR also works for #12 for `boto3.session.Session` takes **credentials** (access, secret, and session), **region_name** (overridable from session.client() and .resource() call, not exposed in watchtower), and **profile_name** (as stated earlier) as its parameter.

**Comment by kislyuk** [comment]
Cool, thanks. I'll tweak this a little bit and push a release shortly.
