### ISSUE TITLE
Use of small time intervals within a stream name (using strftime) fills the conection pool 

### ISSUE THREAD

**Issue by stanorama** [kislyuk/watchtower#111]
"watchtower": {
      "class": "watchtower.CloudWatchLogHandler",
      "level": "DEBUG",
      "formatter": "defaultFormatter",
      "create_log_group": false,
      "log_group": "my_log_group",
      "stream_name": "{ #strftime:%Y/%m/%d/%H/%M/%S/%f} my_log_stream",
      "create_log_stream": true
     }
Reference to PR #71 
This logging config will generate a stream name like: 2020/07/09/20/58/56 my_log_stream.
However the date and time appear to be re-evaluated every time a new message is logged.
This results in a huge number of log streams being created especially when millseconds is set (%f).
This will cause an issue with the connection pool:
Connection pool is full, discarding connection: logs.eu-west-1.amazonaws.com

I believe the stream name should be determined once  when the cloud watch handler is instantiated, so all events for a single run will be added to a single log stream.

**Comment by stanorama** [comment]
Not sure of the impact but I think the following change would resolve

    def emit(self, message):
        if self.creating_log_stream:
            return  # Avoid infinite recursion when asked to log a message as our own side effect
        stream_name = self.stream_name
        if stream_name is None:
            stream_name = message.name
        else:
            stream_name = stream_name.format(logger_name=message.name, strftime=datetime.utcnow())
            #111 Set the class level stream_name, so on the next emit() call it will not be re-evaluated
            self.stream_name = stream_name

**Comment by kislyuk** [comment]
The dynamic evaluation of stream name from the template is a feature, and part of the watchtower API. If you wish to set the stream name statically, then you can evaluate it outside watchtower and pass it to the constructor.
