### ISSUE TITLE
Retry logic is unnecessary and harmful

### ISSUE THREAD

**Issue by mattbsage** [kislyuk/watchtower#113]
G'day,

Just recently started to use Watchtower and noticed that logs were failing to be written to the Cloudwatch log streams.  On inspecting the code, I noticed this curiosity...

```
    def _submit_batch(self, batch, stream_name, max_retries=5):
        if len(batch) < 1:
            return
        sorted_batch = sorted(batch, key=itemgetter('timestamp'), reverse=False)
        kwargs = dict(logGroupName=self.log_group, logStreamName=stream_name,
                      logEvents=sorted_batch)
        if self.sequence_tokens[stream_name] is not None:
            kwargs["sequenceToken"] = self.sequence_tokens[stream_name]
        response = None

        for retry in range(max_retries):
            try:
                response = self.cwl_client.put_log_events(**kwargs)
                break
```

I cannot see a purpose of the ```max_retries``` parameter and loop.  Retries to the Cloudwatch service are already handled automatically in the ```boto``` client.  Additionally, your parameter is never used in code and cannot be configured anywhere. 

I also noticed that these extra retries were flooding the Cloudwatch service and causing brownouts on the log stream, as each log stream is limited to only 5 TPS.

May I suggest you remove the retry logic from your code?

Regards,

Matt

**Comment by kislyuk** [comment]
You make a good point about handling the retries in boto3. However, the logic that you pasted (without the subsequent lines which define which conditions get retried) is designed to only retry on specific conditions that will *not* be handled by built-in retries in boto3 - specifically, sequence token exceptions indicating a race loss, and an absent log stream (requiring just-in-time creation of the log stream).

Brownouts are indeed possible if multiple threads of your application all try to write to the same log stream (and arguably the biggest issue here is that this best practice is not documented in Watchtower). Please assign separate log groups to threads/processes in your application, and if you continue to encounter brownouts, we can think more about what to do to improve the ergonomics here.
