### ISSUE TITLE
CloudWatchLogHandler never updates its sequence token cache

### ISSUE THREAD

**Issue by colini** [kislyuk/watchtower#116]
Hello,

CloudWatchLogHandler creates a sequence_tokens dictionary, which appears to be intended to store CW Log sequence tokens between calls to the PutLogEvents API.  But since this dictionary is never updated, _submit_batch() first calls the API without a token.  This initial call will fail, at which point it correctly parses the expected token from the exception and resubmits the PutLogEvents call.

AFAICT, this means the API is called 2x as many times as necessary.  If configured to not use queues, it would call the API 2x for every single log message.

Before I create a PR I was hoping someone could confirm my reading of the code.  Thanks!

**Comment by kislyuk** [comment]
Thanks for pointing this out. This regression was introduced in https://github.com/kislyuk/watchtower/pull/18 and your analysis appears correct.
