### ISSUE TITLE
Default AWS config / infinite hang

### ISSUE THREAD

**Issue by gbm** [kislyuk/watchtower#128]
The documentation suggests to use this as the default configuration
https://github.com/kislyuk/watchtower/blob/develop/README.rst#examples-python-logging-config
```python
# Default AWS Config
version: 1
formatters:
    json:
        format: "[%(asctime)s] %(process)d %(levelname)s %(name)s:%(funcName)s:%(lineno)s - %(message)s"
    plaintext:
        format: "[%(asctime)s] %(process)d %(levelname)s %(name)s:%(funcName)s:%(lineno)s - %(message)s"
handlers:
    console:
        (): logging.StreamHandler
        level: DEBUG
        formatter: plaintext
        stream: sys.stdout
    watchtower:
        formatter: json
        level: DEBUG
        (): watchtower.CloudWatchLogHandler
        log_group: logger
        stream_name:  loggable
        send_interval: 1
        create_log_group: False
loggers:
    root:
        handlers: [console, watchtower, logfile]
    boto:
        handlers: [console]
    boto3:
        handlers: [console]
    botocore:
        handlers: [console]
    requests:
        handlers: [console]
```

However it seems that when this configuration is used, the root logger is not initialized correctly and must be changed to :

```python
loggers:
    boto:
        handlers: [console]
        propagate: False
    boto3:
        handlers: [console]
        propagate: False
    botocore:
        handlers: [console]
        propagate: False
    requests:
        handlers: [console]
        propagate: False
root:
    handlers: [ console, watchtower, logfile]
```

Additionally the console handler must be changed to 

```python
handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: plaintext
        stream: ext://sys.stdout
```
This last issue seems to have been hit on #53 in April 2019 however it seems this has not been reflected in the documentation. 

Additionally it seems that I am also hitting the bug that others have encountered for example #93 which has been open since April 2020 - I encounter either an infinite recursive loop until the stack limit is hit and the process exits or an infinite hang - depending on whether use_queues is set to True or False. 

These together cause serious concerns for using this package in production.

**Comment by kislyuk** [comment]
Thank you for your feedback. You are correct to point out that the example configuration in the docs was wrong; I have updated it and tested it to ensure it is correct. This also addresses #53. As for #93, please see my comment there for an explanation of what's going on; it's not a bug in Watchtower, although it's understandable that a better behavior is desired out of the box when setting the root logger level to DEBUG with no further settings, and I have released a workaround in v1.0.2.

To your comment about your concerns, Watchtower is used in a number of production environments and will hopefully be used in many more. I am proud of the level of quality and stability that this package has achieved with the help of its contributors. Constructive feedback and especially PRs are welcome.
