### ISSUE TITLE
Could not do a head request, falling back to regular pull.

### ISSUE THREAD

**Issue by jwillmer** [kislyuk/watchtower#130]
I'm using a private GitHub registry and my logs are flooded by this message. Can I get rid of it somehow so that my notifications won't show this message all the time?

**Comment by kislyuk** [comment]
Hi - could you please clarify how this issue pertains to Watchtower?

**Comment by jwillmer** [comment]
`docker logs watchtower`
![image](https://user-images.githubusercontent.com/1503577/102816870-ff457c80-43ce-11eb-9de8-70a588e7b9bf.png)

**Comment by kislyuk** [comment]
You seem to be using watchtower as part of a different application. What you're seeing is logs from that application (performing a Docker image pull, it seems). Please don't file issues here; instead, file them with the application that you are experiencing problems with.

**Comment by jwillmer** [comment]
@kislyuk I don't understand. I use watchtower to update my containers and watchtower logs output the above messages. How is this not a problem of watchtower?

**Comment by kislyuk** [comment]
OK, I think you're looking for a different project named watchtower then.

**Comment by jwillmer** [comment]
Oh, so sorry! I didn't noticed that this is a different project :dizzy_face:
