### ISSUE TITLE
Watchtower in AWS Lambda packages redundantly pulls in boto3

### ISSUE THREAD

**Issue by joseph-wortmann** [kislyuk/watchtower#133]
Thank you for this very cool project!

Because a Python Lambda package is the zipped sum of the full dependency tree of package requirements, and because Watchtower lists "boto3" as an install_requires, Lambda packages including watchtower become seriously bloated (because boto3 + it's dependencies is pretty big).

The Lambda execution environment for Python already provides boto3 inherently and keeps it up-to-date with changes to the AWS API. Including boto3 in a Lambda package is redundant. Furthermore, since the packaged boto3 version is static, sometimes drift in the AWS API can cause weird errors to happen (like your unchanged Lambda function failing all of a sudden).

I see three ways to fix this:

1. Fork watchtower, remove boto3, and release a lambda-watchtower version to PyPI. I'd rather not do this, as it requires tracking the main project when releases occur.
2. Remove boto3 altogether from the watchtower install_requires, note it in the documentation, and call it a day. Note that anyone using watchtower that forgets to install boto3 (outside of Lambda, obviously) should figure out their error pretty quickly.
3. Make boto3 an extras_require, not an install_requires, package, and document the same.

I'm willing to do any of the three, I prefer number 2. If the watchtower maintainer(s) want either 2 or 3, then I'll do that and submit a PR for main project inclusion.

**Comment by nraghuveer** [comment]
For point 2, If boto3 is removed, there might be an issue with maintaining compatibility or upgrades with boto3
For point 3, seems like an approach, but the existing users have to explicitly change this in their scripts and thus can break few installs.

@joseph-wortmann, have you tried lambda packaging tools like `chalice` or `zappa`? These take care of removing boto3 from the dependencies.

**Comment by kislyuk** [comment]
@joseph-wortmann we are not going to remove boto3 from the dependencies, since watchtower depends on boto3 😄 

@nraghuveer is absolutely right to suggest chalice - it's what I use for all my Lambda apps and recommend to others for managing Python Lambda projects. Chalice has a number of dependency management features, including this.
