### ISSUE TITLE
create_log_group=True throws an exception if log group already exists

### ISSUE THREAD

**Issue by ashutoshsingh0223** [kislyuk/watchtower#136]
If I have already created the log group I want to write logs to. The default `create_log_group=True` throws an exception.
`ValueError: Unable to configure handler 'cloudwatch': An error occurred (OperationAbortedException) when calling the CreateLogGroup operation: A conflicting operation is currently in progress against this resource. Please try again.`

**Comment by kislyuk** [comment]
Thank you for reporting this. This error condition arises when there is a race between multiple log writers trying to create the same log group simultaneously. I have added a catch so that this error does not cause the logger to crash. I will roll a patch release once the tests complete.
