### ISSUE TITLE
Log streams created by same code for different times all have same data and last event time when code finishes

### ISSUE THREAD

**Issue by shayanalibhatti** [kislyuk/watchtower#145]
Hi, thanks for the great work on this project. I am having an issue that when my code logs to AWS based on each time it executes, then it does create different streams of different times as shown on AWS cloudwatch. But when i kill the code, then all streams eventually get the same data and their last event time also becomes the same. Why is that? How should I avoid that ? 

Here is the code. It runs in a cron job every 5 minutes and logs all data that is sent via logging.info() but gives the above mentioned issue.

```    
# For cloudwatch logging stream
    dt = datetime.datetime.now(datetime.timezone.utc)
    new_dt = datetime.datetime.strftime(dt,format="%Y_%m_%d %H_%M_%S")
    logger = logging.getLogger()
    log_handler = watchtower.CloudWatchLogHandler(boto3_session = boto3_session,log_group=log_name,stream_name=str(new_dt))
    logger.addHandler(log_handler)
    logger.setLevel('INFO')
```

**Comment by kislyuk** [comment]
Hello, thank you for your interest in Watchtower. Your report does not provide enough detail to reproduce the issue. I am going to close this issue for now. Please feel free to open a new issue with a complete piece of code necessary to reproduce your problem if you still need help.

**Comment by shayanalibhatti** [comment]
Hi,

Never mind, I think I solved this issue a while back, can't remember
how, its been 5 months now.

Regards,
Shayan Ali Bhatti.
