### ISSUE TITLE
Only logs from a given class is being sent to cloudwatch

### ISSUE THREAD

**Issue by ericchaves** [kislyuk/watchtower#147]
Hi, I'm using your awesome lib to stream logs to cloudwatch but I'm doing something wrong and couldn't figure out what is. Forgive me for asking such newbiew question in here.

I have two classes both belonging to the same module (ie declared on the same __init__.py module): ​Each class creates it's own logger and attaches a cloudwatch handler to it in addition to stdandart console output handler, however only the logs from the first class are being sent to cloudwatch. No logs from the second class appears. On the console however logs from all classes are printed.

At first I thougth it could be something related to the logging level (which I set directly on child loggers and not on the root) but it does not seems to be the case.

Can  you think on anything I may b e doing wrong?

The code is more or less like this (some parts truncated for readability):

```
import os
import logging
import watchtower

LOGLEVEL = os.environ.get('LOGLEVEL', 'INFO').upper()
logging.basicConfig(
    format='%(asctime)s %(name)s %(levelname)-8s %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S' )

class service:
  def __init__(self, config_file):
      self.config_file = config_file
      self.logger = logging.getLogger(root_logger)
      self.logger.setLevel(LOGLEVEL)
      if 'cloudwatch' in servico:
       # I've tried to share the service.cloudwatcher with service's tasks and also to instantiate new handlers. neither worked.
        self.cloudwatch_handler=watchtower.CloudWatchLogHandler(log_group=self.log_group, stream_name=self.log_str)
        self.cloudwatch_handler.setLevel(LOGLEVEL)
        self.logger.addHandler(self.cloudwatch_handler)
      else:
        self.cloudwatch_handler = None

class task:
  def __init__(self, service):
      self.logger = logging.getLogger(self.nome)
      if servico.cloudwatch_handler:
        self.logger.addHandler(servico.cloudwatch_handler)
        servico.cloudwatch_handler.setLevel(logging.DEBUG)

service.do_something() # <-- logs inside this method do show-up in cloudwatch and on the console
for task in service.tasks:
  task.do_something() # <-- logs inside this method do not show-up in cloudwatch but are sent to console as expected
```

**Comment by kislyuk** [comment]
Hi, thanks for your interest in watchtower. Your question is not specific to watchtower but is general to the Python logging system. Please check the documentation for the Python logging module and make sure that your loggers are set to propagate messages to the root logger.
