### ISSUE TITLE
Feature request: Rolling Log Streams

### ISSUE THREAD

**Issue by Nogginboink** [kislyuk/watchtower#150]
I'm using Watchtower on a long-running (days) process. It would be nice if Watchtower could automatically roll to a new log stream on a preconfigured interval.

**Comment by nrmilstein** [comment]
I believe you can do this. Set `'stream_name': '{strftime:%Y-%m-%d %Z}'` and it will create a new stream every day.

**Comment by kislyuk** [comment]
As @nrmilstein mentioned, this is supported. Let us know if this doesn't suit your needs.
