### ISSUE TITLE
Allow passing botocore's Config or a CW client directly (to customize timeouts, retries, etc)

### ISSUE THREAD

**Issue by tuukkamustonen** [kislyuk/watchtower#151]
Even though `CloudWatchLogHandler(..., boto3_session=)` is supported, one cannot configure timeouts, retries, etc. that are set in `botocore.config.Config()` instance and passed in client construction like `boto3.client('logs', config=config)`.

So, allow `CloudWatchLogHandler(..., botocore_config=...)` too, or `CloudWatchLogHandler(..., cw_client=...)` to pass in an already created client instance.

(`boto3_profile_name=` does not help here, because that would require entry in a config file... which not everyone has).

**Comment by kislyuk** [comment]
Hello, thanks for your interest in this. Yes, the client should really be customizable just as session is, either via subclassing or via a kwarg. Happy to accept a PR for that.

The custom retry logic is there for a reason; as far as I recall, it's necessary when multiple processes use the same sequence token after forking.

**Comment by kislyuk** [comment]
Thanks for raising this issue. This has been implemented and will be released in v2.0.0.
