### ISSUE TITLE
Django Watchtower connection refused when running server localhost

### ISSUE THREAD

**Issue by cyzanfar** [kislyuk/watchtower#155]
I am using Django [watchtower][1] to log events to Cloudwatch and have configured my logging in my settings file.

__development.py__

    boto3_session = Session(
        aws_access_key_id=AWS_ACCESS_KEY_ID,
        aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
        region_name=AWS_REGION)
    
    
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        # 'root': {
        #     'level': 'INFO',
        #     'handlers': ['console'],
        # },
        'formatters': {
            'simple': {
                'format': "%(asctime)s [%(levelname)-8s] %(message)s",
                'datefmt': "%Y-%m-%d %H:%M:%S"
            },
            'aws': {
                # you can add specific format for aws here
                'format': "%(asctime)s [%(levelname)-8s] %(message)s",
                'datefmt': "%Y-%m-%d %H:%M:%S"
            },
        },
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
            },
            'watchtower': {
                'level': 'INFO',
                'class': 'watchtower.CloudWatchLogHandler',
                'boto3_session': boto3_session,
                'log_group': 'StagingBeagleApi',
                'stream_name': 'ApplicationLogStream',
                'formatter': 'aws',
            },
        },
        'loggers': {
            'django': {
                'level': 'INFO',
                'handlers': ['watchtower'],
                'propagate': True,
            },
        },
    }

However when I run my server, I don't get any error in the console but my site is not accessible anymore via locahost:3000, I get an `ERR_CONNECTION_REFUSED`

Please help!

**UPDATE**

If I replace the `django` key with `watchtower` it works. However, I want to put all Django logs into Cloudwatch and I followed the documentation which has the logger key as `django`.

  [1]: https://pypi.org/project/watchtower/

**Comment by cyzanfar** [comment]
Hey update on that?

**Comment by kislyuk** [comment]
Thank you for your interest in watchtower. This library is free software and I provide support when I have time to do so. The sponsor button is at the top and bottom of this page if you want to support the development of watchtower.

**Comment by kislyuk** [comment]
@abhanan93 this happens in the Django development server because it breaks threading. I have updated the documentation for watchtower with a new recommended Django configuration that avoids this problem.

**Comment by spetoolio** [comment]
Might be worth mentioning that when we upgraded from 0.7.3 to 3.0.0, we encountered this problem on localhost, but also encountered it on staging when using uwsgi. So seems like it may be a broader issue.
