### ISSUE TITLE
Python logging format not working with Cloud Watch Log Handler

### ISSUE THREAD

**Issue by Rahul-V-Maxval** [kislyuk/watchtower#163]
import watchtower, logging, boto3
logging.basicConfig(level=logging.INFO, format='%(asctime)s|%(levelname)s|%(message)s',)
logger = logging.getLogger()
boto3_client_obj=boto3.client('logs', region_name="us-west-2")
logger.addHandler(watchtower.CloudWatchLogHandler(log_group_name='watchtower', log_stream_name='loggable',
                                                  boto3_client=boto3_client_obj))
logger.info("Hi")

### The resulting raw CloudWatch Log event looks like this:
{
"timestamp": 1636868049692,
 "message": 'Hi',
 "ingestionTime": 1636868050028
}

**Comment by kislyuk** [comment]
logging.basicConfig is not sufficiently flexible for this task. Instead you need:
```
import watchtower, logging, boto3
formatter = logging.Formatter('%(asctime)s|%(levelname)s|%(message)s')
cloud_handler = watchtower.CloudWatchLogHandler()
cloud_handler.setFormatter(formatter)
console_handler = logging.StreamHandler()
console_handler.setFormatter(formatter)
logging.basicConfig(level=logging.INFO, handlers=[console_handler, cloud_handler])
logger = logging.getLogger()
logger.info("Hi")
```
