### ISSUE TITLE
handler not sending batch messages when `use_queues=True` to Cloudwatch

### ISSUE THREAD

**Issue by nabsabraham** [kislyuk/watchtower#164]
If I set `use_queues=True` I don't get my logs pushed to Cloudwatch. However, when I set `use_queues=False` I can see my log stream created. I'm currently using `watchtower==2.0.0`. I've inspected the queue and it seems there's always only one item in the queue for my log_stream but its not getting dequeued. Since my stream is not large, I can get away with sending messages one at a time but need a long-term fix.

**Comment by kislyuk** [comment]
Thank you for your interest in Watchtower. Your report does not provide sufficient information to reproduce the problem. If you need help, please provide a complete, self-contained reproduction of your problem.

I am going to close this issue for now. Please feel free to provide the required information here and I will reopen, or file a new one.

**Comment by MichaelKim0407** [comment]
https://stackoverflow.com/a/76284801/3248736

@kislyuk I wrote down my diagnosis on StackOverflow. Please take a look
