### ISSUE TITLE
endpoint_url support removed since v2.0.0

### ISSUE THREAD

**Issue by Exagone313** [kislyuk/watchtower#170]
Hello,

We've been using watchtower (v1.0.6) to send some logs into CloudWatch Logs and it works well. In development, we use localstack to be able to use this feature locally. It works by setting an `endpoint_url` parameter when creating various boto3 objects.

Since v2.0.0, this feature got removed, it was introduced in #114.

Is it an overlook that happened in the refactoring, or is it wanted behavior not to support custom CloudWatch Logs implementations?

Thanks.

**Comment by kislyuk** [comment]
The endpoint_url option remains supported by way of the boto3_client option as documented here: https://kislyuk.github.io/watchtower/#watchtower.CloudWatchLogHandler
