### ISSUE TITLE
Django set-up [Documentation]

### ISSUE THREAD

**Issue by omonimus1** [kislyuk/watchtower#173]
```
boto3_logs_client = boto3.client("logs", region_name=AWS_REGION_NAME)
```
Can you please guys make a set-up example for django application, with explicit log group and log stream name.
Then, go do we have just boto3.client(), if most of the guides for watchtower nows requires:
```
CLOUDWATCH_AWS_ID = env("CLOUDWATCH_AWS_ID")
CLOUDWATCH_AWS_KEY = env("CLOUDWATCH_AWS_KEY")
logger_boto3_session = Session(
 aws_access_key_id=CLOUDWATCH_AWS_ID,
 aws_secret_access_key=CLOUDWATCH_AWS_KEY,
 region_name='eu-west-2',
)
```

**Comment by Cyb3rFl3x** [comment]
This would be quite nice, I'm trying to get in running since 2 days and I do not understand it yet...

**Comment by omonimus1** [comment]
@cyb3rFI3x, here:https://faun.pub/logging-in-django-and-metrics-building-into-aws-cloudwatch-f4145eceed20

**Comment by Cyb3rFl3x** [comment]
🙏

**Comment by kislyuk** [comment]
Thank you for your interest in Watchtower. The documentation already has a section that comprehensively covers Django setup.
