### ISSUE TITLE
Why do some of the particular timestamp logs not appear in CloudWatch Logs?

### ISSUE THREAD

**Issue by rabinshribin** [kislyuk/watchtower#177]
When I run my lambda function usually it prints logs as I excepted which is the usual thing. Now I had noticed that there is a log missing of specific timestamp. It is not because of throttling. If this happened because of throttle I had set that lambda will try until it succeed. I haven`t found the solution and I could not find a way to troubleshoot the problem.My lambda has been printed successfully same operation now and there is no issue.

**Comment by kislyuk** [comment]
Thanks for your interest in Watchtower. What you describe does not sound like an issue with this library, so I'm going to close this issue now.
