### ISSUE TITLE
watchtower is blocking app from reserving port to run

### ISSUE THREAD

**Issue by yalattas** [kislyuk/watchtower#188]
We have Python `Django==3.2` application deployed to many platforms as a test.

Watchtower causes the application not to reserve port during `python manage.py runserver 0.0.0.0:8000`

The above behavior is happening only with AWS ECS Fargate platform, Fargate team confirmed that nothing from Fargate platform is blocking that port

We have deployed the application with Watchtower on EC2, Beanstalk and EKS and it was working fine

After we deployed it to ECS Fargate, it stopped working.
When we disabled Watchtower from our app, app starts working on ECS Fargate.

**Comment by kislyuk** [comment]
Thanks for your interest in watchtower. This library does not listen on any ports and your report does not provide sufficient information to reproduce the issue that you experienced.

I am going to close this issue now. If you need help, please post a full minimal set of steps necessary to reproduce the issue, including the full code and a listing of its dependencies, the behavior observed, and the behavior expected.
