### ISSUE TITLE
Use unique stream_name by default

### ISSUE THREAD

**Issue by jinty** [kislyuk/watchtower#19]
I've been using watchtower with it's default stream names and been getting InvalidSequenceTokenException from CloudWatch on a regular basis because multiple writers are using the same stream_name. There is some more explanation here:

https://forums.aws.amazon.com/thread.jspa?messageID=651619

I think the default of having the stream name be the "the name of the logger that processed the message" is poor and it should probably contain some unique id. Perhaps a uuid or uuid+timestamp? AWS Lambda uses this form for the stream name: 2016/03/17/[$LATEST]0bd45fd38b204db6864797217eec1d7c

That said, I really liked the idea of having the stream name be the logger name, it's a nice browse experience in the CloudWatch console. Just not going to work out very well :(

**Comment by kislyuk** [comment]
Two things:
- I welcome PRs that set the log stream default to `__name__ + "/" + instance_id + process_id` or similar. I'm short on time so won't get to it until next week at the earliest.
- Currently the code tries retrieving the latest token and resubmitting the batch once. It should be OK (and reasonably cheap) to retry at least a dozen times.

**Comment by aventurella** [comment]
Any status on this?

**Comment by kislyuk** [comment]
I haven't run into this problem myself, so I haven't produced a solution. I don't have a strong preference for what kind of name to select. @aventurella, does `__name__ + "/" + instance_id + process_id` work for you?

PRs welcome as always.

**Comment by aventurella** [comment]
I will let my own ignorance speak here, I don't know that I necessarily understand how the stream name is relevant. I'm not doubting it I'm literally ignorant to the internal operation of it. So to me any name is fine =)  Is it just the log stream name?

**Comment by kislyuk** [comment]
When you log messages to CloudWatch Logs, you specify two keys for what log "bucket" your messages go into: log group and log stream. If multiple writers write to the same stream, they encounter a race condition and have to retry submitting the messages, causing an unnecessary performance issue and, in case of too many writers, a crash.

To solve this problem, we have to assign a unique name to each writer. As pointed out above, Lambda uses what looks like a uuid at the end of its log stream name. I'd like at least the prefix of the name to be deterministic, if not the whole name, e.g. watchtower/logger-name/instance-id/process-id.

**Comment by aventurella** [comment]
ah... ok following... let me review the source and see if I can come up with a PR. I'm in a launch crunch time, so no promises but this is the 2nd deployment I have done where I have seen this error (using gunicorn + gevent workers x 3+)  So I'm motivated to address it.

**Comment by kislyuk** [comment]
If you're in a rush, you don't have to patch this library to avoid the `InvalidSequenceTokenException` errors. Just assign the stream name manually, like this:
```
import watchtower, logging, socket

logging.basicConfig(level=logging.INFO)
handler = watchtower.CloudWatchLogHandler(stream_name=str(socket.gethostname()) + "." + str(os.getpid()))
app.logger.addHandler(handler)
```

**Comment by aventurella** [comment]
I love you! I didn't think to look...

**Comment by aventurella** [comment]
Question, does that error actually effect the running application or is it safe to ignore?

**Comment by bedge** [comment]
I'm running into this too. 
Here's a similar use case, so assuming not worthy of a separate bug.

Is it possible to use the watchtower.CloudWatchLogHandler() handler in a log.cfg file that's specified on the gunicorn command line, ala:
```
/usr/local/bin/gunicorn --bind unix:ml-api.sock -m 007 --workers=8  --log-config=/opt/nim/ml-api/log.cfg --log-level=DEBUG app
```

If so, what are the args that it accepts?
ie, in log.cfg:
```
[handler_log_file]
class=watchtower.CloudWatchLogHandler
args=(.....)

```

**Comment by aventurella** [comment]
Here's how I do in in the JSON log configuration format:

```python
LOGGING['handlers']['cloud'] = {
        'formatter': 'verbose',
        'level': 'DEBUG',
        '()': 'watchtower.CloudWatchLogHandler',
        # kwargs to watchtower.CloudWatchLogHandler
        'log_group': env('AWS_CLOUDWATCH_LOG_GROUP'),
        'send_interval': 10
    }
```

**Comment by philippbosch** [comment]
fyi: 4da3e8140502d34da5b4ad6404b95fc92f655427 introduced an even better way to configure a unique stream name, e.g.:

```python
watchtower.CloudWatchLogHandler(stream_name="{logger_name}." + str(socket.gethostname()) + "." + str(os.getpid()))

# …

import logging
logger = logging.getLogger('my_name')
logger.info('blah blah')
```

will use a stream name like `my_name.6b0164f650ec.1`

**Comment by kislyuk** [comment]
The default stream name will remain as is; stream name parameterization facilities have been documented.
