### ISSUE TITLE
How to integrate watchtower into scrapy?

### ISSUE THREAD

**Issue by clown-0726** [kislyuk/watchtower#200]
How to integrate watchtower into scrapy?

**Comment by kislyuk** [comment]
Hello, thank you for your interest in Watchtower.

I don't know anything about scrapy and I'm not sure what your goals are in integrating the two. If you have specific questions about how to configure Watchtower with a specific goal in mind, please describe that and what you have tried so far.

I'm going to close this issue for now as it does not seem to indicate any problem with Watchtower or a valid request for support. Please feel free to comment and we can reopen as necessary.
