### ISSUE TITLE
Please cut a new release

### ISSUE THREAD

**Issue by chaines-ps** [kislyuk/watchtower#24]
Could you please cut a new release? The flag to disable log group creation would be very useful, but it is much more difficult to use when not in PyPi.

Thanks!

**Comment by kislyuk** [comment]
Should be fixed in v0.3.3, please test.

**Comment by kislyuk** [comment]
(Sorry about the inconvenience!)

**Comment by chaines-ps** [comment]
Awesome! Thanks for the fast response!
