### ISSUE TITLE
Split into separate "logging" and "batch handling" parts

### ISSUE THREAD

**Issue by nickrw** [kislyuk/watchtower#26]
Hello,

I'm going to be using watchtower for as-is as a logging.Handler, but I also wanted to make use of its batch-handling queues for importing old data into cloudwatch logs. To do the latter I'm going to have to separate the concerns of log handling and queue/batching.

If I were to separate our the log handling from the queue/batch (with the log handling using the new separate queue/batch) would you be interested in that PR?

**Comment by kislyuk** [comment]
Thanks for asking. I would be glad to merge that, as long as the design is compact and readable and has tests included.

**Comment by nickrw** [comment]
Great thanks.

One other thing, I notice you disabled a few PEP8 warnings, would you care if some or all of them are "fixed" in the process? :)

**Comment by kislyuk** [comment]
I'm not opposed to fixing pep8 warnings.

**Comment by kislyuk** [comment]
It looks like this was never followed up on and the feature is not in demand; closing.
