### ISSUE TITLE
Take down https://pycwl.readthedocs.org/en/latest/ ?

### ISSUE THREAD

**Issue by solarce** [kislyuk/watchtower#4]
https://pycwl.readthedocs.org/en/latest/ is still floating around but then you end up at a 404 on github for https://github.com/kislyuk/pycwl/

As the project owner I think you need to initiate the old name's removal on RTD

**Comment by garnaat** [comment]
+1

I found the link for pycwl on readthedocs and then, when I couldn't find it on github and all of the links were broken I assumed it must be dead.  Fortunately, @solarce pointed me in the right direction.

**Comment by kislyuk** [comment]
Thanks for the heads up on this. Fixed now (after https://github.com/rtfd/readthedocs.org/issues/1701).
