### ISSUE TITLE
JSON data to CloudWatch...

### ISSUE THREAD

**Issue by BenjamenMeyer** [kislyuk/watchtower#40]
I've got watchtower working; however, we want to be sending JSON data up instead of the plaintext line. It looks like watchtower should honor the formatter, but you don't show any examples of how to setup a formatter. Guidance on doing the more formal Python logging would be appreciated.

**Comment by BenjamenMeyer** [comment]
Okay, so the `logging.config.dictConfig` actually integrates watchtower pretty nicely; but the one thing that would be extremely helpful would be to provide a configuration section name kwarg as an alternative to the `boto3_session` kwarg

**Comment by BenjamenMeyer** [comment]
PR #41 is in response to https://github.com/kislyuk/watchtower/issues/40#issuecomment-315208987 - however, I still do need some help validating everything.

**Comment by kislyuk** [comment]
Looks like there is nothing remaining to do here, closing.
