### ISSUE TITLE
Creating log streams is blocking the main thread

### ISSUE THREAD

**Issue by dahlia** [kislyuk/watchtower#50]
Unlike `batch_sender()`, creating a log stream is currently blocking the main thread.  Even though this operation is infrequent, it could affect to the rest of the application when CloudWatch itself is experiencing outage or serious performance issues; indeed that's what I experienced today.  😫

I wonder @kislyuk's thoughts about the idea to make log stream creation nonblocking.  If it's appropriate I'd like to submit a patch!

**Comment by kislyuk** [comment]
Thanks for filing the report.

Doesn't the answer to this depend on whether your application considers logging to be critical? Some applications require logging for auditability purposes, and operating without logging is worse than not operating at all. Maybe this should be an option, but would it be on or off by default?

**Comment by dahlia** [comment]
The case of my app is actually not considering logging to be critical.  The problem was that logging has anyway worked well and the most of logging codes have written with the assumption that logging is always successful, or at least doesn't raise any exceptions.

If it's from scratch there would be also another way to make the parameter required, but since we have many users I think the appropriate way is to maintain the behavior it has worked: off by default.

**Comment by cngo-github** [comment]
Having the option to queue up the logs until AWS is restored would be fantastic in case of downtime.

**Comment by kislyuk** [comment]
Closing this issue. Creation of log streams does not block the main thread unless `use_queues` is set to False (which is not recommended and should only be used for debugging). The work to make this logic more resilient to network outages is being tracked in #119.
