### ISSUE TITLE
Stream Not Created / Logs not written DJango 2

### ISSUE THREAD

**Issue by mdaymond** [kislyuk/watchtower#54]
I have the following configuration:

```
boto3_session = Session(aws_access_key_id=AWS_ACCESS_KEY_ID,
                        aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
                        region_name=AWS_REGION_NAME)


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'root': {
        'level': LOG_LEVEL,
        'handlers': ['console'],
    },
    'formatters': {
        'simple': {
            'format': u"%(asctime)s [%(levelname)-8s] %(message)s",
            'datefmt': "%Y-%m-%d %H:%M:%S"
        },
        'aws': {
            # you can add specific format for aws here
            'format': u"%(asctime)s [%(levelname)-8s] %(message)s",
            'datefmt': "%Y-%m-%d %H:%M:%S"
        },
    },

    'handlers': {
        'watchtower': {
            'level': LOG_LEVEL,
            'class': 'watchtower.CloudWatchLogHandler',
            'boto3_session': boto3_session,
            'log_group': 'MyLogGroup',
            'create_log_group': False,
            'stream_name': 'ops',
            'formatter': 'aws',
        },
        'console': {
            'class': 'logging.StreamHandler',
        }
    },
    'loggers': {
        'django': {
            'level': LOG_LEVEL,
            'handlers': ['watchtower'],
            'propagate': False,
        },
        # add your other loggers here...
    },
}
```

When I send my logs, I see that the "MyLogGroup" is created, but not the stream and therefore no logs either.    When i turn on debugging for botocore, I see the following:

```
Loading variable region from instance vars with value 'us-west-2'.
Loading variable profile from defaults.
Loading variable ca_bundle from defaults.
Loading variable profile from defaults.
Loading variable api_versions from defaults.
Loading variable profile from defaults.
Event choose-service-name: calling handler <function handle_service_name_alias at 0x10ca50048>
Event creating-client-class.logs: calling handler <function add_generate_presigned_url at 0x10ca1a9d8>
The s3 config key is not a dictionary type, ignoring its value of: None
Setting logs timeout as (60, 60)
Registering retry handlers for service: logs
```

I confirm when I run the configuration through this set of commands everything works as expected:
import watchtower, logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)
logger.addHandler(watchtower.CloudWatchLogHandler())
logger.info("Hi")

So it seems to me that the handler is not being registered correctly

**Comment by kislyuk** [comment]
I'm not a Django expert and I don't operate Django apps, so I personally can't help you much. I would try replacing LOGGING.handlers.watchtower.class with logging.StreamHandler to verify that it actually logs to console as expected when using a standard handler.

**Comment by mdaymond** [comment]
Thanks.  I confirmed that works as expected.

**Comment by alexfoster** [comment]
@mbeacom This worked for me. Had to reuse IAM user for both my static files stuff and for this cloudwatch logging because the django watchtower module doesnt seem to use boto sessions properly. Minor though

**Comment by divick** [comment]
I did exactly what @mbeacom did but still I get the similar error message in logs with it complaining that "The s3 config key is not a dictionary type, ignoring its value of: None"

> [2019-02-14 15:05:26,283] DEBUG [hooks:_alias_event_name:417 406] Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
> [2019-02-14 15:05:26,302] DEBUG [hooks:_alias_event_name:417 406] Changing event name from before-call.apigateway to before-call.api-gateway
> [2019-02-14 15:05:26,305] DEBUG [hooks:_alias_event_name:417 406] Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
> [2019-02-14 15:05:26,315] DEBUG [hooks:_alias_event_name:417 406] Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
> [2019-02-14 15:05:26,316] DEBUG [hooks:_alias_event_name:417 406] Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
> [2019-02-14 15:05:26,318] DEBUG [hooks:_alias_event_name:417 406] Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
> [2019-02-14 15:05:26,322] DEBUG [hooks:_alias_event_name:417 406] Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
> [2019-02-14 15:05:26,337] DEBUG [hooks:_alias_event_name:417 406] Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
> [2019-02-14 15:05:26,338] DEBUG [hooks:_alias_event_name:417 406] Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
> [2019-02-14 15:05:26,338] DEBUG [hooks:_alias_event_name:417 406] Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
> [2019-02-14 15:05:26,339] DEBUG [hooks:_alias_event_name:417 406] Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
> [2019-02-14 15:05:26,340] DEBUG [session:set_config_variable:294 406] Setting config variable for region to 'us-east-2'
> [2019-02-14 15:05:26,346] DEBUG [loaders:load_file:174 406] Loading JSON file: /usr/local/lib/python3.6/site-packages/botocore/data/endpoints.json
> [2019-02-14 15:05:26,363] DEBUG [hooks:_emit:210 406] Event choose-service-name: calling handler <function handle_service_name_alias at 0x7f72e937f620>
> [2019-02-14 15:05:26,415] DEBUG [loaders:load_file:174 406] Loading JSON file: /usr/local/lib/python3.6/site-packages/botocore/data/logs/2014-03-28/service-2.json
> [2019-02-14 15:05:26,429] DEBUG [hooks:_emit:210 406] Event creating-client-class.cloudwatch-logs: calling handler <function add_generate_presigned_url at 0x7f72e93b6b70>
> [2019-02-14 15:05:26,430] DEBUG [args:compute_s3_config:169 406] The s3 config key is not a dictionary type, ignoring its value of: None
> [2019-02-14 15:05:26,435] DEBUG [endpoint:create_endpoint:266 406] Setting logs timeout as (60, 60)
> [2019-02-14 15:05:26,439] DEBUG [loaders:load_file:174 406] Loading JSON file: /usr/local/lib/python3.6/site-packages/botocore/data/_retry.json
> [2019-02-14 15:05:26,441] DEBUG [client:_register_retries:139 406] Registering retry handlers for service: logs
> 

I tried to dig deeper into what is happening and I see that the credentials stored in session are not used at all when it calls create_client from within boto3/session.py. Apparently it worked for @mbeacom because somehow his keys are getting picked up from environment or somewhere else which has no direct bearing on passing them to DjangoCloudWatchLogHandler. I will try to dig further and see what is happening.

**Comment by kojima** [comment]
I've resolved this issue by setting `use_queues: False` for `watchtower` handler like below:
```
'watchtower': {
        'level': os.getenv('DJANGO_LOG_LEVEL', 'ERROR'),
        'class': 'watchtower.CloudWatchLogHandler',
        'boto3_session': boto3_session,
        'log_group': '<log group>',
        'stream_name': '<stream name>',
        'formatter': 'verbose',
        'use_queues': False,   # <--- This setting resolves the issue
},
```
Hope this setting also resolves your problem.

**Comment by NikolasOliveira** [comment]
Thanks for this tip, setting use_queues to False has saved me in multiple situations now.

Has anyone been able to find the root cause of the issue with queuing?

**Comment by terencehonles** [comment]
It looks like [boto3 sessions are not thread safe](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/resources.html#multithreading-and-multiprocessing) and session objects should be created per thread. I've not seen the error mentioned here and while poking around at different things I believe I may have seen that the situation may have improved so I might suggest making sure you are on the most recent release.

That may be barking up the wrong tree, but I do not use `DjangoCloudWatchLogHandler` and my use case looks more like what the OP has and it is working for me (using queues too). I am having some problems with forking, but it looks like that is directly related to locking and that doesn't necessarily seem like it's the same issue here.

**Comment by kislyuk** [comment]
@terencehonles thanks, this is a good point; I should probably just go ahead and use per-thread boto3 clients unless a custom one was passed in at init time.

**Comment by soheelhaque** [comment]
Thank you @kojima, setting use_queues to False worked for me too. I too would be interested in why queues cause an issue with Django (or at least some Django apps).

**Comment by emacstheviking** [comment]
The ` 'use_queues': False,` worked fror me too... for the record my configuration looks like this now, and works fine for what I need, before it worked, it was hanging somewhere... Django would print out the startup message and look like it was running but the /admin/ pages were not up, for example.

Ignore the graphqwl_filter, that's mine.

```
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        "formatters": {
            "verbose": {
                "format": "%(asctime)s %(levelname)-8s %(module)s: %(message)s"
            },
            "aws": {
                "format": "%(asctime)s %(levelname)-8s %(message)s -- %(pathname)s:%(lineno)d",
                "datefmt": "%Y-%m-%d %H:%M:%S",
            },
        },
        'filters': {
            'graphql_filter': {
                '()': 'api.filters.graphql_filter.GraphQLFilter',
            },
        },
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
                'filters': ['graphql_filter'],
                'formatter': 'aws',
            },
            "watchtower": {
                "level": "INFO",  # INFO on prod
                "class": "watchtower.CloudWatchLogHandler",
                "boto3_session": logger_boto3_session,
                "log_group": "DjangoLOCAL",  # change for: ProdDjangoLogs
                "stream_name": f"api",
                "formatter": "aws",
                'use_queues': False,
                'filters': ['graphql_filter'],
            },
        },
        'root': {
            'handlers': ['watchtower', 'console'],
            'level': 'INFO',
        },
        "loggers": {
            # Use this logger to send data just to Cloudwatch
            "watchtower": {
                "level": "INFO",
                "handlers": ["watchtower"],
                "propogate": False,
            }
        },
    }

```

**Comment by frat3rius** [comment]
@emacstheviking the same situation here. Django starts but it's not accepting requests (from what I've tested it actually doesn't bind to port at all, which was very hard to debug). I didn't managed to figure out why watchtower stopped working (when I played around with watchtower during setup process everything seems to be working correctly). After a while it behave like that and I didn't connected it with watchtower at first.

For me only adding 'use_queues': False allows me to use watchtower. I'm also using boto3 for django storages maybe there's some conflict between sessions. Not sure how to debug it though.

**Comment by emacstheviking** [comment]
@frat3rius puzzling isn't it. I thought it was when I ran in debug mode as opposed to normal mode but I have just tested with it running in either mode and it seems fine now. It was very puzzling, it had all the feelings of a socket timeout taking place. The other odd thing was that the react based UI I have was complaining about CORS issues and not trying to log me on (the thing I was testing) at all which only added to the confusion but I think that was because Django was not accepting requests.

If I get some time I will attempt to debug into the Watchtower code -- something -- is hanging on startup and causing Django to report itself as running but not running!

<<< ten minutes later >>>

OK, after repeated trial and trace with breakpoints and stepping through the code I know WHERE it is hanging but not why... in this file: (I'm on a mac):
/usr/local/Cellar/python@3.7/3.7.11/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py

It is hanging on ...
```
def _acquireLock():
    """
    Acquire the module-level lock for serializing access to shared data.

    This should be released with _releaseLock().
    """
    if _lock:
        _lock.acquire()
```
which was called from `isEnabledFor` (line 1614, same file), which is called from (in same file)
```
    def debug(self, msg, *args, **kwargs):
        """
        Log 'msg % args' with severity 'DEBUG'.

        To pass exception information, use the keyword argument exc_info with
        a true value, e.g.

        logger.debug("Houston, we have a %s", "thorny problem", exc_info=1)
        """
        if self.isEnabledFor(DEBUG):
            self._log(DEBUG, msg, args, **kwargs)
```
which was called from the `run` method in file:
py37/lib/python3.7/site-packages/django/utils/autoreload.py

It never returns form this initial attempt to CALL A LOG FUNCTION !!!
```
    def run(self, django_main_thread):
        logger.debug('Waiting for apps ready_event.')
    : 
    : 

```
The logical conclusion is that somewhere, somehow, something has either screwed up the lock mechanism or there is some kind of deadlock at work... that's as far as I can go with it for now. Got work piling up.

I hope that helps somebody else get to the root cause of this problem. It ONLY seems to happen when the use_queues flag is True, I guess that's the place to start loooking.
HTH

**Comment by kislyuk** [comment]
The previous recommended Django configuration would cause a deadlock when running the django development server. The recommended Django configuration has been updated to note and work around this issue.

Please note that setting use_queues to False in production is not recommended, since it will cause performance issues   due to the synchronous sending of one CloudWatch API request per log message.
