### ISSUE TITLE
Document Use of Group, Stream, and Other Parameters in Basic Example

### ISSUE THREAD

**Issue by Miserlou** [kislyuk/watchtower#55]
The basic (non-Django/Flask) example gives no examples of using any of the `log_group`, `stream_name`, `use_queues`, `send_interval`, `max_batch_size`, `max_batch_count`, `boto3_session`, `boto3_profile_name`, and `create_log_group` settings.

These are pretty important and the only way to see how they work is by reading the code!

The basic example could be extended to show some simple usage of these parameters.

**Comment by kislyuk** [comment]
These parameters are documented in the API documentation.
