### ISSUE TITLE
Add `create_log_stream` boolean option

### ISSUE THREAD

**Issue by Miserlou** [kislyuk/watchtower#56]
There is currently a `create_log_group` option, which is great, but no corresponding `create_log_stream` option. This is managed outside of my application, so watchtower will never be able to create a log stream.

**Comment by monspid** [comment]
We have the same problem. Any NEWS?

**Comment by francoisfreitag** [comment]
I think this issue was solved with #77?

**Comment by kislyuk** [comment]
Yes, thanks, this was addressed.
