### ISSUE TITLE
Split in different streams and rotation

### ISSUE THREAD

**Issue by esseti** [kislyuk/watchtower#60]
Hi there,
I've a question that is actually two questions, but related:
- is it possible to have rotation as per files? lilke a new stream everyday?
- is there a possibility to have a stream for each user? even modifying the code, i just want to know if it's feasbile. the data that i'm logging are a json and I could extract the user id from there and the send to the specific stream. would this be feasible?

**Comment by esseti** [comment]
for the second part, i did this (not sure if it's efficient enough, feedbacks are welcomed).
I created a new class extending the CloudWatchLogHandler and I copied the emit adding this at the beginning. the rest remains the same.

```
    def emit(self, message):
        # edit to retreive name from the message
        t_msg = message.msg
        stream_name = 'unknown'
        # if it's string, then it's probably a json.dumps
        if isinstance(t_msg, str):
            try:
                t_msg = json.load(t_msg)
            except:
                pass
        #  if it's a dict, search for the user
        if isinstance(t_msg, dict):
            stream_name = t_msg['user']
        #end edit
```

**Comment by kislyuk** [comment]
If you need direct control over the stream name, you can use multiple log handlers and explicitly specify the stream that you like in each handler's constructor. @ajhodges also added a time-based dynamic formatting facility to stream names so streams can be rotated over any time interval supported by the strftime formatter.
