### ISSUE TITLE
Is there any support for ec2 roles?

### ISSUE THREAD

**Issue by melontron** [kislyuk/watchtower#64]
Is there any support for ec2 roles? I can't setup region without providing credentials in ~/.aws/credentials file. Is it possible to do it with ec2 roles and setup region programmatically?

**Comment by melontron** [comment]
I've figured it out how to do, using ~/.aws/config

**Comment by kislyuk** [comment]
Watchtower uses whatever credentials you have set using standard boto3 procedure. It also supports passing a custom session via the `boto3_session` keyword argument in the constructor.
