### ISSUE TITLE
SSL validation failed errors

### ISSUE THREAD

**Issue by akx** [kislyuk/watchtower#67]
I've recently started getting

> Failed to deliver logs: SSL validation failed for https://logs.eu-west-1.amazonaws.com/ unknown error (_ssl.c:3946)

warnings, interspersed with

> Failed to deliver logs: None

and none of my logs get delivered.

This is in an app that's packaged into a `python:3.7.0-stretch` Docker container; furthermore, `requests.get('https://logs.eu-west-1.amazonaws.com/')` from within the container (run locally) seems to work fine.

Looking for a resolution, but if anyone has any idea, I'm all ears.

**Comment by kislyuk** [comment]
This is a transport error that is most likely related to an issue with your SSL library or network configuration. Watchtower does not configure SSL or service endpoints; it relies on boto3/botocore and its dependencies to do so. You could try updating boto3/botocore to see if the issue goes away.

The relevant issue here is actually that watchtower fails to produce a legible error message in the log when this happens.
