### ISSUE TITLE
watchtower not logging Asynchronously to Cloudwatch 

### ISSUE THREAD

**Issue by parmeshbhande** [kislyuk/watchtower#68]
While using watchtower to push logs on cloudwatch , it is not sending logs async. Because of this system getting slow down

**Comment by kislyuk** [comment]
Watchtower does log asynchronously if you use the default configuration (`use_queues=True`). If you observe a specific scenario where log messages are not queued but logged synchronously instead, then please provide more information about how to reproduce this issue.
