### ISSUE TITLE
Timeout when running from VPC lambda no NAT

### ISSUE THREAD

**Issue by areksiekiera** [kislyuk/watchtower#82]
Does watchtower need internet connection or is it using boto3 to connect to CloudWatch? 
```
cloudwatch_handler = watchtower.CloudWatchLogHandler(
                        log_group=app.config['LOG_GROUP_NAME'], 
                        stream_name=app.config['STAGE'],
                        use_queues=False)
logger.addHandler(cloudwatch_handler)
```
This causes lambda to times out with no error message. 
Any clue?

**Comment by kislyuk** [comment]
1. Watchtower requires an internet connection.

2. You don't need Watchtower in a Lambda, just use the built-in logging.

**Comment by kislyuk** [comment]
Just to clarify further:

Watchtower uses boto3 to connect to CloudWatch Logs. Boto3 requires an Internet connection.
