### ISSUE TITLE
logging handler configs are ignored (watchtower 0.7.3)

### ISSUE THREAD

**Issue by ramialbatal** [kislyuk/watchtower#83]
Hi, I am using the following config to set my loggers:

```
[handlers]
keys=FileHandler,WatchtowerHandler

[handler_FileHandler]
class=handlers.RotatingFileHandler
formatter=formatter
maxBytes=1024
backupCount=10
args=(eval('__import__("os").getcwd()+"/mylog.log"'), 'a+')

[handler_WatchtowerHandler]
class=watchtower.CloudWatchLogHandler
formatter=formatter
send_interval=1
log_group=my_log_group
stream_name=my_stream_name
args=()

[formatters]
keys=formatter

[formatter_formatter]
format=%(asctime)s [%(threadName)-12.12s] [%(levelname)-5.5s]  %(message)s

[loggers]
keys=root

[logger_root]
level=INFO
handlers=FileHandler,WatchtowerHandler
```

The `stream_name` created in cloudwatch log is always `root`, and the `log_group` is always `watchtower`, so the `stream_name=my_stream_name` and `log_group=my_log_group` configs are ignored.

**Comment by czekan** [comment]
If you're using python >= 3.7 (cpython) you can pass kwargs to `watchtower.CloudWatchLogHandler`  (https://github.com/python/cpython/pull/2979) like that
```
[handler_watchtower]
class = watchtower.CloudWatchLogHandler
args = () 
kwargs = {'log_group': 'your_log_group', 'stream_name': 'your_stream_name', 'send_interval': 5, 'boto3_profile_name': 'default', 'log_group_retention_days': 90}
formatter = formatter
```
You can pass any other `CloudWatchLogHandler` init params as well (https://github.com/kislyuk/watchtower/blob/master/watchtower/__init__.py#L107).

But if you're stuck on python 3.6 or lower version than you probably need to put `args` in a correct order:

```
[handler_watchtower]
class = watchtower.CloudWatchLogHandler
args = ('your_log_group', 'your_stream_name', True, 5, .........) 
formatter = formatter
```
as `kwargs` param is not supported there.

**Comment by kislyuk** [comment]
Thanks for your help @czekan. I hope this addresses your issue @ramialbatal. I'm going to close this issue now since the intricacies of Python logging config loading are outside the scope of this package.
