### ISSUE TITLE
Logger gives UnicodeEncodeError when it tries to log characters like ä

### ISSUE THREAD

**Issue by akshatbjain** [kislyuk/watchtower#95]
Hi,

First of all, thanks a lot for creating watchtower. It is really really helpful.

I am facing a string encoding error when characters like "ä" are used which are not in the "English alphabet".

My guess (based on the error I see) is due to the encoding type not being right. 

Error:
`UnicodeEncodeError: 'ascii' codec can't encode character '\xe4' in position 26214987: ordinal not in range(128)`

Seems like watchtower is trying to use "ascii" instead of "utf-8". Is there a way I can set the encoding to "utf-8", I couldn't find any option for that.

Thanks and Regards,
Akshat

**Comment by kislyuk** [comment]
You can avoid these issues by switching to Python 3. Python 2 is no longer supported.

**Comment by akshatbjain** [comment]
I am using Python 3.5 but it still gives this error!

**Comment by kislyuk** [comment]
OK, thanks for clarifying. Please post a full reproduction of the issue that you see.

**Comment by kislyuk** [comment]
To be clear, you are already using utf-8 if you use Python 3.5. The error that you posted indicates that either you are not actually using Python 3.5 (this should be clear from the stack trace), or your application is setting the encoding to ascii somewhere.
